#
# Copyright (C) 2022 Curity AB. All rights reserved.
#
# The contents of this file are the property of Curity AB.
# You may not copy or use this file, in either source code
# or executable form, except in compliance with terms
# set by Curity AB.
#
# For further information, please contact Curity AB.
#

country-codes.DZ=Argélia
country-codes.AD=Andorra
country-codes.AO=Angola
country-codes.AI=Anguilla
country-codes.AG=Antigua e Barbuda
country-codes.AR=Argentina
country-codes.AM=Armênia
country-codes.AW=Aruba
country-codes.AU=Austrália
country-codes.AT=Áustria
country-codes.AZ=Azerbaijão
country-codes.BS=Bahamas
country-codes.BH=Bahrain
country-codes.BD=Bangladesh
country-codes.BB=Barbados
country-codes.BY=Belarus
country-codes.BE=Bélgica
country-codes.BZ=Belize
country-codes.BJ=Benin
country-codes.BM=Bermuda
country-codes.BT=Butão
country-codes.BO=Bolívia
country-codes.BA=Bósnia-Herzegovina
country-codes.BW=Botsuana
country-codes.BR=Brasil
country-codes.BN=Brunei
country-codes.BG=Bulgária
country-codes.BF=Burkina Faso
country-codes.BI=Burundi
country-codes.KH=Camboja
country-codes.CM=Camarões
country-codes.CA=Canadá
country-codes.CV=Ilhas de Cabo Verde
country-codes.KY=Ilhas Cayman
country-codes.CF=República Centro-Africana
country-codes.CL=Chile
country-codes.CN=China
country-codes.CO=Colômbia
country-codes.KM=Comores
country-codes.CG=Congo
country-codes.CK=Ilhas Cook
country-codes.CR=Costa Rica
country-codes.HR=Croácia
country-codes.CU=Cuba
country-codes.CY=Chipre
country-codes.CZ=República Tcheca
country-codes.DK=Dinamarca
country-codes.DJ=Djibouti
country-codes.DM=Dominica
country-codes.DO=República Dominicana
country-codes.EC=Equador
country-codes.EG=Egito
country-codes.SV=El Salvador
country-codes.GQ=Guiné Equatorial
country-codes.ER=Eritreia
country-codes.EE=Estonia
country-codes.ET=Etiópia
country-codes.FK=Ilhas Malvinas
country-codes.FO=Ilhas Faroe
country-codes.FJ=Fiji
country-codes.FI=Finlândia
country-codes.FR=França
country-codes.GF=Guiana Francesa
country-codes.PF=Polinésia Francesa
country-codes.GA=Gabão
country-codes.GM=Gâmbia
country-codes.GE=Georgia
country-codes.DE=Alemanha
country-codes.GH=Ghana
country-codes.GI=Gibraltar
country-codes.GR=Grécia
country-codes.GL=Gronelândia
country-codes.GD=Grenada
country-codes.GP=Guadalupe
country-codes.GU=Guam
country-codes.GT=Guatemala
country-codes.GN=Guiné
country-codes.GW=Guiné-Bissau
country-codes.GY=Guiana
country-codes.HT=Haiti
country-codes.HN=Honduras
country-codes.HK=Hong Kong
country-codes.HU=Hungria
country-codes.IS=Islândia
country-codes.IN=Índia
country-codes.ID=Indonésia
country-codes.IR=Irã
country-codes.IQ=Iraque
country-codes.IE=Irlanda
country-codes.IL=Israel
country-codes.IT=Itália
country-codes.JM=Jamaica
country-codes.JP=Japão
country-codes.JO=Jordânia
country-codes.KZ=Cazaquistão
country-codes.KE=Quênia
country-codes.KI=Kiribati
country-codes.KP=Coreia do Norte
country-codes.KR=Coreia do Sul
country-codes.KW=Kuwait
country-codes.KG=Quirguistão
country-codes.LA=Laos
country-codes.LV=Letônia
country-codes.LB=Líbano
country-codes.LS=Lesoto
country-codes.LR=Liberia
country-codes.LY=Líbia
country-codes.LI=Liechtenstein
country-codes.LT=Lituânia
country-codes.LU=Luxemburgo
country-codes.MO=Macau
country-codes.MK=Macedônia
country-codes.MG=Madagascar
country-codes.MW=Malawi
country-codes.MY=Malásia
country-codes.MV=Maldivas
country-codes.ML=Mali
country-codes.MT=Malta
country-codes.MH=Ilhas Marshall
country-codes.MQ=Martinica
country-codes.MR=Mauritânia
country-codes.YT=Mayotte
country-codes.MX=México
country-codes.FM=Micronésia
country-codes.MD=Moldova
country-codes.MC=Mônaco
country-codes.MN=Mongólia
country-codes.MS=Montserrat
country-codes.MA=Marrocos
country-codes.MZ=Moçambique
country-codes.MM=Mianmar
country-codes.NA=Namíbia
country-codes.NR=Nauru
country-codes.NP=Nepal
country-codes.NL=Holanda
country-codes.NC=Nova Caledônia
country-codes.NZ=Nova Zelândia
country-codes.NI=Nicarágua
country-codes.NE=Níger
country-codes.NG=Nigéria
country-codes.NU=Niue
country-codes.NF=Ilhas Norfolk
country-codes.MP=Marianas do Norte
country-codes.NO=Noruega
country-codes.OM=Omã
country-codes.PW=Palau
country-codes.PA=Panamá
country-codes.PG=Papua Nova Guiné
country-codes.PY=Paraguai
country-codes.PE=Peru
country-codes.PH=Filipinas
country-codes.PL=Polônia
country-codes.PT=Portugal
country-codes.PR=Porto Rico
country-codes.QA=Catar
country-codes.RE=Reunion
country-codes.RO=Romênia
country-codes.RU=Rússia
country-codes.RW=Ruanda
country-codes.SM=San Marino
country-codes.ST=São Tomé e Príncipe
country-codes.SA=Arábia Saudita
country-codes.SN=Senegal
country-codes.CS=Sérvia
country-codes.SC=Seychelles
country-codes.SL=Sierra Leone
country-codes.SG=Cingapura
country-codes.SK=República da Eslováquia
country-codes.SI=Eslovênia
country-codes.SB=Ilhas Salomão
country-codes.SO=Somália
country-codes.ZA=África do Sul
country-codes.ES=Espanha
country-codes.LK=Sri Lanka
country-codes.SH=Santa Helena
country-codes.KN=St. Kitts
country-codes.LC=Santa Lúcia
country-codes.SD=Sudão
country-codes.SR=Suriname
country-codes.SZ=Suazilândia
country-codes.SE=Suécia
country-codes.CH=Suíça
country-codes.SY=Síria
country-codes.TW=Taiwan
country-codes.TJ=Tajiquistão
country-codes.TH=Tailândia
country-codes.TG=Togo
country-codes.TO=Tonga
country-codes.TT=Trinidad e Tobago
country-codes.TN=Tunísia
country-codes.TR=Turquia
country-codes.TM=Turcomenistão
country-codes.TC=Ilhas Turks e Caicos
country-codes.TV=Tuvalu
country-codes.UG=Uganda
country-codes.GB=UK
country-codes.UA=Ucrânia
country-codes.AE=Emirados Árabes Unidos
country-codes.UY=Uruguai
country-codes.US=USA
country-codes.UZ=Uzbequistão
country-codes.VU=Vanuatu
country-codes.VA=Cidade do Vaticano
country-codes.VE=Venezuela
country-codes.VN=Vietnã
country-codes.VG=Ilhas Virgens - Britânicas
country-codes.VI=Ilhas Virgens - EUA
country-codes.WF=Wallis e Futuna
country-codes.YE=Iêmen
country-codes.ZM=Zâmbia
country-codes.ZW=Zimbábue
