/*
 * Copyright (C) 2026 Curity AB. All rights reserved.
 *
 * The contents of this file are the property of Curity AB.
 * You may not copy or use this file, in either source code
 * or executable form, except in compliance with terms
 * set by Curity AB.
 *
 * For further information, please contact Curity AB.
 */

import type { SandpackFiles } from '@codesandbox/sandpack-react';
import sdkSource from '../generated/sdkSource.json';
import curityStyles from '../generated/curityStyles.json';
import curityIcons from '../generated/curityIcons.json';
import exampleConfig from '../generated/exampleConfig.json';
import examples from '../generated/examples.json';
import catalog from '../generated/catalog.json';

/**
 * The private dependency closure a HAAPI snippet needs inside Sandpack:
 * - the SDK source under `/node_modules/@curity/haapi-react-sdk/**` (generated by
 *   `scripts/build-sandpack-sdk.mjs`),
 * - the real prebuilt `@curity/ui-kit-icons` bundle, so every icon the SDK (or an example) imports is
 *   available, matching production,
 * - the docs' example catalog at `/catalog.ts` (copied verbatim — the single source of truth for the
 *   canned HAAPI steps, owned by `examples/catalog.ts`),
 * - a mock for `@curity/identityserver-haapi-web-driver` that serves the catalog's steps so the real
 *   `<HaapiStepper>` renders against mock data (no backend, no real driver).
 *
 * `react`/`react-dom` are resolved from the CDN by Sandpack (pinned to 19 by the player).
 */

// Mock web-driver, reusing the docs' example catalog (no duplicated step data). Every example — pinned
// customization steps and browsable showcase steps — is keyed by its `HAAPI_EXAMPLE` value in `EXAMPLES`.
// The boot step is chosen by the URL of the first fetch — `config.bootstrap.initialUrl` carries the key
// (see `examples/config.ts`). A submit (POST) lands on the boot entry's `errorOnSubmit`, or the
// completed step.
const webDriverMock = `import { EXAMPLES, HAAPI_EXAMPLE, completedSuccessStep } from '../../../catalog';
import { HAAPI_PROBLEM_STEPS } from '@curity/haapi-react-sdk/haapi-stepper/data-access/types/haapi-step.types';
import { MEDIA_TYPES } from '@curity/haapi-react-sdk/haapi-stepper/data-access/types/media.types';

const PROBLEM_STEP_TYPES = new Set(Object.values(HAAPI_PROBLEM_STEPS));

const STEP_KEYS = Object.keys(EXAMPLES);

// Authenticator-selection routes: when a selected option's href matches, advance to that authenticator's
// example instead of the boot step, so picking an option in a selector navigates forward (as in
// production).
const FLOW_ROUTES = [
  { match: '/authenticate/user-pwd', step: HAAPI_EXAMPLE.HTML_FORM_LOGIN },
  { match: '/authenticate/email', step: HAAPI_EXAMPLE.EMAIL_OTP },
  // BankID stays on its sticky PENDING wait step (its poll/cancel hrefs also contain '/authenticate/bankid').
  { match: '/authenticate/bankid', step: HAAPI_EXAMPLE.BANKID_WAIT },
];

function toResponse(step) {
  const mediaType = PROBLEM_STEP_TYPES.has(step.type) ? MEDIA_TYPES.PROBLEM : MEDIA_TYPES.AUTH;
  return new Response(JSON.stringify(step), { status: 200, headers: { 'Content-Type': mediaType } });
}

export function createHaapiFetch() {
  // The boot step is set from the first GET (its url is config.bootstrap.initialUrl, '/<key>') and stays
  // sticky, so polling re-fetches keep returning the same PENDING step. Longer keys are matched first so a
  // nested slug ('authenticators/email/otp') wins over a substring of a shorter key.
  const matchKeys = [...STEP_KEYS].sort((a, b) => b.length - a.length);
  let current = EXAMPLES[HAAPI_EXAMPLE.HTML_FORM_LOGIN];
  const fetchLike = (url, init) => {
    const method = (init?.method ?? 'GET').toUpperCase();
    if (method === 'GET') {
      const route = FLOW_ROUTES.find(({ match }) => String(url).includes(match));
      const key = route ? route.step : matchKeys.find(stepKey => String(url).includes(stepKey));
      if (key) {
        current = EXAMPLES[key];
      }
      return Promise.resolve(toResponse(current.step));
    }
    return Promise.resolve(toResponse(current.errorOnSubmit ?? completedSuccessStep));
  };
  fetchLike.init = () => Promise.resolve(fetchLike);
  fetchLike.close = () => undefined;
  return fetchLike;
}
`;

export const haapiClosureFiles: SandpackFiles = {
  ...(sdkSource as Record<string, string>),
  // The docs' example catalog, copied verbatim (single source of truth). Imported by the web-driver mock
  // (`../../../catalog`) and by `/StepSelect.tsx` + `/ExamplePreviewer.tsx` (`./catalog`).
  '/catalog.ts': catalog as string,
  // Shared example config, imported by snippets as `./config` (kept out of the visible `/App.tsx`).
  '/config.ts': exampleConfig as string,
  // Preview chrome imported by the HaapiStepperPreview snippet (`./ExamplePreviewer`, which in turn
  // imports `./StepSelect`, `./StepDataDetails`, `./AutoSubmitForm`, `./config`, `./catalog`). Sourced
  // from the generated examples map so they stay in sync with the docs example components.
  '/ExamplePreviewer.tsx': (examples as Record<string, string>).ExamplePreviewer,
  '/StepSelect.tsx': (examples as Record<string, string>).StepSelect,
  // The collapsed "See step data" JSON panel `ExamplePreviewer` renders below the form.
  '/StepDataDetails.tsx': (examples as Record<string, string>).StepDataDetails,
  // Auto-submit helper, imported by ExamplePreviewer as `./AutoSubmitForm`; clicks a form's submit once
  // after mount so error steps (e.g. validation) surface their post-submit UI in the preview.
  '/AutoSubmitForm.tsx': (examples as Record<string, string>).AutoSubmitForm,
  // The react-ts template's entry already imports `./styles.css`; override it with the Curity CSS so
  // the SDK's `.haapi-stepper-*` / `.field` / `.button` classes are styled like production. A little
  // body padding is appended so the rendered step isn't flush against the preview pane's edges.
  '/styles.css': `${curityStyles as string}\n\nbody { padding: 1.5rem; box-sizing: border-box; }\n`,
  '/node_modules/@curity/ui-kit-icons/package.json': JSON.stringify({
    name: '@curity/ui-kit-icons',
    version: '1.0.0',
    main: 'index.js',
  }),
  '/node_modules/@curity/ui-kit-icons/index.js': curityIcons as string,
  '/node_modules/@curity/identityserver-haapi-web-driver/package.json': JSON.stringify({
    name: '@curity/identityserver-haapi-web-driver',
    version: '1.3.0',
    main: 'index.ts',
  }),
  '/node_modules/@curity/identityserver-haapi-web-driver/index.ts': webDriverMock,
};
