import {
  AddDeviceToAccountByAccountIdDocument,
  UpdateDeviceFromAccountByAccountIdDocument,
  DeleteOptInMfaFactorFromAccountByAccountIdDocument,
  ResetOptInMfaStateByAccountIdDocument,
  UpdateAccountByIdDocument,
  CreateAccountDocument,
  DeleteAccountByIdDocument,
  DeleteDeviceFromAccountByAccountIdDocument,
  GetAccountByUserNameDocument,
  GetAccountsDocument,
  GetAccountsWithoutSortingDocument,
  GetAccountByIdDocument,
  GetAccountByPhoneNumberDocument,
  DeleteLinkFromAccountByAccountIdDocument,
  CompleteVerifyEmailAddressByAccountIdDocument,
  CompleteVerifyTotpDeviceByAccountIdDocument,
  DeleteEmailAddressByAccountIdDocument,
  StartVerifyEmailAddressByAccountIdDocument,
  StartVerifyTotpDeviceByAccountIdDocument,
  UpdatePrimaryEmailAddressByAccountIdDocument,
  DeletePhoneNumberByAccountIdDocument,
  UpdatePrimaryPhoneNumberByAccountIdDocument,
  StartVerifyPhoneNumberByAccountIdDocument,
  CompleteVerifyPhoneNumberByAccountIdDocument,
  GetCredentialPolicyDocument,
  ValidatePasswordAndUpdateAccountByIdDocument,
  AddOptInMfaFactorToAccountByAccountIdDocument,
  CompleteOptInMfaResetRecoveryCodesByAccountIdDocument,
  CompleteOptInMfaSetupByAccountIdDocument,
  OptOutFromOptInMfaByAccountIdDocument,
  StartOptInMfaResetRecoveryCodesByAccountIdDocument,
  StartOptInMfaSetupByAccountIdDocument,
  CompleteVerifyPasskeyByAccountIdDocument,
  StartVerifyPasskeyByAccountIdDocument,
} from '../graphql-codegen-typings-queries-and-mutations/graphql';

export enum USER_MANAGEMENT_API_OPERATIONS {
  // QUERIES
  GET_ACCOUNT_BY_USERNAME = 'getAccountByUserName',
  GET_ACCOUNTS = 'getAccounts',
  GET_ACCOUNTS_WITHOUT_SORTING = 'getAccountsWithoutSorting',
  GET_ACCOUNT_BY_ID = 'getAccountById',
  GET_ACCOUNT_BY_PHONE_NUMBER = 'getAccountByPhoneNumber',
  GET_CREDENTIAL_POLICY = 'getCredentialPolicy',

  // MUTATIONS
  ADD_DEVICE_TO_ACCOUNT_BY_ACCOUNT_ID = 'addDeviceToAccountByAccountId',
  UPDATE_DEVICE_FROM_ACCOUNT_BY_ACCOUNT_ID = 'updateDeviceFromAccountByAccountId',
  DELETE_OPT_IN_MFA_FACTOR_FROM_ACCOUNT_BY_ACCOUNT_ID = 'deleteOptInMfaFactorFromAccountByAccountId',
  RESET_OPT_IN_MFA_STATE_BY_ACCOUNT_ID = 'resetOptInMfaStateByAccountId',
  UPDATE_ACCOUNT_BY_ID = 'updateAccountById',
  CREATE_ACCOUNT = 'createAccount',
  DELETE_ACCOUNT_BY_ID = 'deleteAccountById',
  DELETE_DEVICE_FROM_ACCOUNT_BY_ACCOUNT_ID = 'deleteDeviceFromAccountByAccountId',
  DELETE_LINK_FROM_ACCOUNT_BY_ACCOUNT_ID = 'deleteLinkFromAccountByAccountId',
  START_VERIFY_TOTP_DEVICE = 'startVerifyTotpDeviceByAccountId',
  COMPLETE_VERIFY_TOTP_DEVICE = 'completeVerifyTotpDeviceByAccountId',
  START_VERIFY_EMAIL_ADDRESS = 'startVerifyEmailAddressByAccountId',
  COMPLETE_VERIFY_EMAIL_ADDRESS = 'completeVerifyEmailAddressByAccountId',
  DELETE_EMAIL_ADDRESS = 'deleteEmailAddressByAccountId',
  UPDATE_PRIMARY_EMAIL_ADDRESS = 'updatePrimaryEmailAddressByAccountId',
  START_VERIFY_PHONE_NUMBER = 'startVerifyPhoneNumberByAccountId',
  COMPLETE_VERIFY_PHONE_NUMBER = 'completeVerifyPhoneNumberByAccountId',
  DELETE_PHONE_NUMBER = 'deletePhoneNumberByAccountId',
  UPDATE_PRIMARY_PHONE_NUMBER = 'updatePrimaryPhoneNumberByAccountId',
  VALIDATE_PASSWORD_AND_UPDATE_ACCOUNT_BY_ID = 'validatePasswordAndUpdateAccountById',
  ADD_OPT_IN_MFA_FACTOR_TO_ACCOUNT_BY_ACCOUNT_ID = 'addOptInMfaFactorToAccountByAccountId',
  OPT_OUT_FROM_OPT_IN_MFA_BY_ACCOUNT_ID = 'optOutFromOptInMfaByAccountId',
  START_OPT_IN_MFA_SETUP_BY_ACCOUNT_ID = 'startOptInMfaSetupByAccountId',
  COMPLETE_OPT_IN_MFA_SETUP_BY_ACCOUNT_ID = 'completeOptInMfaSetupByAccountId',
  START_OPT_IN_MFA_RESET_RECOVERY_CODES_BY_ACCOUNT_ID = 'startOptInMfaResetRecoveryCodesByAccountId',
  COMPLETE_OPT_IN_MFA_RESET_RECOVERY_CODES_BY_ACCOUNT_ID = 'completeOptInMfaResetRecoveryCodesByAccountId',
  START_VERIFY_PASSKEY = 'startVerifyPasskeyByAccountId',
  COMPLETE_VERIFY_PASSKEY = 'completeVerifyPasskeyByAccountId',
}

export const USER_MANAGEMENT_API = {
  QUERIES: {
    [USER_MANAGEMENT_API_OPERATIONS.GET_ACCOUNT_BY_USERNAME]: GetAccountByUserNameDocument,
    [USER_MANAGEMENT_API_OPERATIONS.GET_ACCOUNTS]: GetAccountsDocument,
    [USER_MANAGEMENT_API_OPERATIONS.GET_ACCOUNTS_WITHOUT_SORTING]: GetAccountsWithoutSortingDocument,
    [USER_MANAGEMENT_API_OPERATIONS.GET_ACCOUNT_BY_ID]: GetAccountByIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.GET_ACCOUNT_BY_PHONE_NUMBER]: GetAccountByPhoneNumberDocument,
    [USER_MANAGEMENT_API_OPERATIONS.GET_CREDENTIAL_POLICY]: GetCredentialPolicyDocument,
  },
  MUTATIONS: {
    [USER_MANAGEMENT_API_OPERATIONS.ADD_DEVICE_TO_ACCOUNT_BY_ACCOUNT_ID]: AddDeviceToAccountByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.UPDATE_DEVICE_FROM_ACCOUNT_BY_ACCOUNT_ID]:
      UpdateDeviceFromAccountByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_OPT_IN_MFA_FACTOR_FROM_ACCOUNT_BY_ACCOUNT_ID]:
      DeleteOptInMfaFactorFromAccountByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.RESET_OPT_IN_MFA_STATE_BY_ACCOUNT_ID]: ResetOptInMfaStateByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.UPDATE_ACCOUNT_BY_ID]: UpdateAccountByIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.CREATE_ACCOUNT]: CreateAccountDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_ACCOUNT_BY_ID]: DeleteAccountByIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_DEVICE_FROM_ACCOUNT_BY_ACCOUNT_ID]:
      DeleteDeviceFromAccountByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_LINK_FROM_ACCOUNT_BY_ACCOUNT_ID]: DeleteLinkFromAccountByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.START_VERIFY_TOTP_DEVICE]: StartVerifyTotpDeviceByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.COMPLETE_VERIFY_TOTP_DEVICE]: CompleteVerifyTotpDeviceByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.START_VERIFY_EMAIL_ADDRESS]: StartVerifyEmailAddressByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.COMPLETE_VERIFY_EMAIL_ADDRESS]: CompleteVerifyEmailAddressByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_EMAIL_ADDRESS]: DeleteEmailAddressByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.UPDATE_PRIMARY_EMAIL_ADDRESS]: UpdatePrimaryEmailAddressByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.START_VERIFY_PHONE_NUMBER]: StartVerifyPhoneNumberByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.COMPLETE_VERIFY_PHONE_NUMBER]: CompleteVerifyPhoneNumberByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_PHONE_NUMBER]: DeletePhoneNumberByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.UPDATE_PRIMARY_PHONE_NUMBER]: UpdatePrimaryPhoneNumberByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.VALIDATE_PASSWORD_AND_UPDATE_ACCOUNT_BY_ID]:
      ValidatePasswordAndUpdateAccountByIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.OPT_OUT_FROM_OPT_IN_MFA_BY_ACCOUNT_ID]: OptOutFromOptInMfaByAccountIdDocument,

    [USER_MANAGEMENT_API_OPERATIONS.ADD_OPT_IN_MFA_FACTOR_TO_ACCOUNT_BY_ACCOUNT_ID]:
      AddOptInMfaFactorToAccountByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.START_OPT_IN_MFA_SETUP_BY_ACCOUNT_ID]: StartOptInMfaSetupByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.COMPLETE_OPT_IN_MFA_SETUP_BY_ACCOUNT_ID]: CompleteOptInMfaSetupByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.START_OPT_IN_MFA_RESET_RECOVERY_CODES_BY_ACCOUNT_ID]:
      StartOptInMfaResetRecoveryCodesByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.COMPLETE_OPT_IN_MFA_RESET_RECOVERY_CODES_BY_ACCOUNT_ID]:
      CompleteOptInMfaResetRecoveryCodesByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.START_VERIFY_PASSKEY]: StartVerifyPasskeyByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.COMPLETE_VERIFY_PASSKEY]: CompleteVerifyPasskeyByAccountIdDocument,
  },
};
