import {
  AddDeviceToAccountByAccountIdDocument,
  UpdateDeviceFromAccountByAccountIdDocument,
  DeleteOptInMfaFactorFromAccountByAccountIdDocument,
  ResetOptInMfaStateByAccountIdDocument,
  UpdateAccountByIdDocument,
  CreateAccountDocument,
  DeleteAccountByIdDocument,
  DeleteDeviceFromAccountByAccountIdDocument,
  GetAccountByUserNameDocument,
  GetAccountsDocument,
  GetAccountsWithoutSortingDocument,
  GetAccountByIdDocument,
  GetAccountByPhoneNumberDocument,
  DeleteLinkFromAccountByAccountIdDocument,
  CompleteVerifyEmailAddressDocument,
  CompleteVerifyTotpDeviceDocument,
  DeleteEmailAddressDocument,
  StartVerifyEmailAddressDocument,
  StartVerifyTotpDeviceDocument,
  UpdatePrimaryEmailAddressDocument,
  DeletePhoneNumberDocument,
  UpdatePrimaryPhoneNumberDocument,
  StartVerifyPhoneNumberDocument,
  CompleteVerifyPhoneNumberDocument,
  GetCredentialPolicyDocument,
  ValidatePasswordAndUpdateAccountByIdDocument,
  CompleteVerifyPasskeyDocument,
  StartVerifyPasskeyDocument,
} from '../graphql-codegen-typings-queries-and-mutations/graphql';

export enum USER_MANAGEMENT_API_OPERATIONS {
  // QUERIES
  GET_ACCOUNT_BY_USERNAME = 'getAccountByUserName',
  GET_ACCOUNTS = 'getAccounts',
  GET_ACCOUNTS_WITHOUT_SORTING = 'getAccountsWithoutSorting',
  GET_ACCOUNT_BY_ID = 'getAccountById',
  GET_ACCOUNT_BY_PHONE_NUMBER = 'getAccountByPhoneNumber',
  GET_CREDENTIAL_POLICY = 'getCredentialPolicy',

  // MUTATIONS
  ADD_DEVICE_TO_ACCOUNT_BY_ACCOUNT_ID = 'addDeviceToAccountByAccountId',
  UPDATE_DEVICE_FROM_ACCOUNT_BY_ACCOUNT_ID = 'updateDeviceFromAccountByAccountId',
  DELETE_OPT_IN_MFA_FACTOR_FROM_ACCOUNT_BY_ACCOUNT_ID = 'deleteOptInMfaFactorFromAccountByAccountId',
  RESET_OPT_IN_MFA_STATE_BY_ACCOUNT_ID = 'resetOptInMfaStateByAccountId',
  UPDATE_ACCOUNT_BY_ID = 'updateAccountById',
  CREATE_ACCOUNT = 'createAccount',
  DELETE_ACCOUNT_BY_ID = 'deleteAccountById',
  DELETE_DEVICE_FROM_ACCOUNT_BY_ACCOUNT_ID = 'deleteDeviceFromAccountByAccountId',
  DELETE_LINK_FROM_ACCOUNT_BY_ACCOUNT_ID = 'deleteLinkFromAccountByAccountId',
  START_VERIFY_TOTP_DEVICE = 'startVerifyTotpDevice',
  COMPLETE_VERIFY_TOTP_DEVICE = 'completeVerifyTotpDevice',
  START_VERIFY_EMAIL_ADDRESS = 'startVerifyEmailAddress',
  COMPLETE_VERIFY_EMAIL_ADDRESS = 'completeVerifyEmailAddress',
  DELETE_EMAIL_ADDRESS = 'deleteEmailAddress',
  UPDATE_PRIMARY_EMAIL_ADDRESS = 'updatePrimaryEmailAddress',
  START_VERIFY_PHONE_NUMBER = 'startVerifyPhoneNumber',
  COMPLETE_VERIFY_PHONE_NUMBER = 'completeVerifyPhoneNumber',
  DELETE_PHONE_NUMBER = 'deletePhoneNumber',
  UPDATE_PRIMARY_PHONE_NUMBER = 'updatePrimaryPhoneNumber',
  VALIDATE_PASSWORD_AND_UPDATE_ACCOUNT_BY_ID = 'validatePasswordAndUpdateAccountById',
  START_VERIFY_PASSKEY = 'startVerifyPasskey',
  COMPLETE_VERIFY_PASSKEY = 'completeVerifyPasskey',
}

export const USER_MANAGEMENT_API = {
  QUERIES: {
    [USER_MANAGEMENT_API_OPERATIONS.GET_ACCOUNT_BY_USERNAME]: GetAccountByUserNameDocument,
    [USER_MANAGEMENT_API_OPERATIONS.GET_ACCOUNTS]: GetAccountsDocument,
    [USER_MANAGEMENT_API_OPERATIONS.GET_ACCOUNTS_WITHOUT_SORTING]: GetAccountsWithoutSortingDocument,
    [USER_MANAGEMENT_API_OPERATIONS.GET_ACCOUNT_BY_ID]: GetAccountByIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.GET_ACCOUNT_BY_PHONE_NUMBER]: GetAccountByPhoneNumberDocument,
    [USER_MANAGEMENT_API_OPERATIONS.GET_CREDENTIAL_POLICY]: GetCredentialPolicyDocument,
  },
  MUTATIONS: {
    [USER_MANAGEMENT_API_OPERATIONS.ADD_DEVICE_TO_ACCOUNT_BY_ACCOUNT_ID]: AddDeviceToAccountByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.UPDATE_DEVICE_FROM_ACCOUNT_BY_ACCOUNT_ID]:
      UpdateDeviceFromAccountByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_OPT_IN_MFA_FACTOR_FROM_ACCOUNT_BY_ACCOUNT_ID]:
      DeleteOptInMfaFactorFromAccountByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.RESET_OPT_IN_MFA_STATE_BY_ACCOUNT_ID]: ResetOptInMfaStateByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.UPDATE_ACCOUNT_BY_ID]: UpdateAccountByIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.CREATE_ACCOUNT]: CreateAccountDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_ACCOUNT_BY_ID]: DeleteAccountByIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_DEVICE_FROM_ACCOUNT_BY_ACCOUNT_ID]:
      DeleteDeviceFromAccountByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_LINK_FROM_ACCOUNT_BY_ACCOUNT_ID]: DeleteLinkFromAccountByAccountIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.START_VERIFY_TOTP_DEVICE]: StartVerifyTotpDeviceDocument,
    [USER_MANAGEMENT_API_OPERATIONS.COMPLETE_VERIFY_TOTP_DEVICE]: CompleteVerifyTotpDeviceDocument,
    [USER_MANAGEMENT_API_OPERATIONS.START_VERIFY_EMAIL_ADDRESS]: StartVerifyEmailAddressDocument,
    [USER_MANAGEMENT_API_OPERATIONS.COMPLETE_VERIFY_EMAIL_ADDRESS]: CompleteVerifyEmailAddressDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_EMAIL_ADDRESS]: DeleteEmailAddressDocument,
    [USER_MANAGEMENT_API_OPERATIONS.UPDATE_PRIMARY_EMAIL_ADDRESS]: UpdatePrimaryEmailAddressDocument,
    [USER_MANAGEMENT_API_OPERATIONS.START_VERIFY_PHONE_NUMBER]: StartVerifyPhoneNumberDocument,
    [USER_MANAGEMENT_API_OPERATIONS.COMPLETE_VERIFY_PHONE_NUMBER]: CompleteVerifyPhoneNumberDocument,
    [USER_MANAGEMENT_API_OPERATIONS.DELETE_PHONE_NUMBER]: DeletePhoneNumberDocument,
    [USER_MANAGEMENT_API_OPERATIONS.UPDATE_PRIMARY_PHONE_NUMBER]: UpdatePrimaryPhoneNumberDocument,
    [USER_MANAGEMENT_API_OPERATIONS.VALIDATE_PASSWORD_AND_UPDATE_ACCOUNT_BY_ID]:
      ValidatePasswordAndUpdateAccountByIdDocument,
    [USER_MANAGEMENT_API_OPERATIONS.START_VERIFY_PASSKEY]: StartVerifyPasskeyDocument,
    [USER_MANAGEMENT_API_OPERATIONS.COMPLETE_VERIFY_PASSKEY]: CompleteVerifyPasskeyDocument,
  },
};
