#
# Copyright (C) 2016 Curity AB. All rights reserved.
#
# The contents of this file are the property of Curity AB.
# You may not copy or use this file, in either source code
# or executable form, except in compliance with terms
# set by Curity AB.
#
# For further information, please contact Curity AB.
#

country-codes.DZ=Algeriet
country-codes.AD=Andorra
country-codes.AO=Angola
country-codes.AI=Anguilla
country-codes.AG=Antigua &amp; Barbuda
country-codes.AR=Argentina
country-codes.AM=Armenien
country-codes.AW=Aruba
country-codes.AU=Australien
country-codes.AT=Österrike
country-codes.AZ=Azerbajdzjan
country-codes.BS=Bahamas
country-codes.BH=Bahrain
country-codes.BD=Bangladesh
country-codes.BB=Barbados
country-codes.BY=Vitryssland
country-codes.BE=Belgien
country-codes.BZ=Belize
country-codes.BJ=Benin
country-codes.BM=Bermuda
country-codes.BT=Bhutan
country-codes.BO=Bolivia
country-codes.BA=Bosnien Hercegovina
country-codes.BW=Botswana
country-codes.BR=Brasilien
country-codes.BN=Brunei
country-codes.BG=Bulgarien
country-codes.BF=Burkina Faso
country-codes.BI=Burundi
country-codes.KH=Kambodja
country-codes.CM=Kamerun
country-codes.CA=Kanada
country-codes.CV=Kap Verdeöarna
country-codes.KY=Caymanöarna
country-codes.CF=Centralafrikanska republiken
country-codes.CL=Chile
country-codes.CN=Kina
country-codes.CO=Colombia
country-codes.KM=Komorerna
country-codes.CG=Kongo
country-codes.CK=Cooköarna
country-codes.CR=Costa Rica
country-codes.HR=Kroatien
country-codes.CU=Kuba
country-codes.CY=Cypern
country-codes.CZ=Tjeckien
country-codes.DK=Danmark
country-codes.DJ=Djibouti
country-codes.DM=Dominica
country-codes.DO=Dominikanska republiken
country-codes.EC=Ecuador
country-codes.EG=Egypten
country-codes.SV=El Salvador
country-codes.GQ=Ekvatorialguinea
country-codes.ER=Eritrea
country-codes.EE=Estland
country-codes.ET=Etiopien
country-codes.FK=Falklandsöarna
country-codes.FO=Färöarna
country-codes.FJ=Fiji
country-codes.FI=Finland
country-codes.FR=Frankrike
country-codes.GF=Franska Guyana
country-codes.PF=Franska Polynesien
country-codes.GA=Gabon
country-codes.GM=Gambia
country-codes.GE=Georgien
country-codes.DE=Tyskland
country-codes.GH=Ghana
country-codes.GI=Gibraltar
country-codes.GR=Grekland
country-codes.GL=Grönland
country-codes.GD=Grenada
country-codes.GP=Guadeloupe
country-codes.GU=Guam
country-codes.GT=Guatemala
country-codes.GN=Guinea
country-codes.GW=Guinea - Bissau
country-codes.GY=Guyana
country-codes.HT=Haiti
country-codes.HN=Honduras
country-codes.HK=Hong Kong
country-codes.HU=Ungern
country-codes.IS=Island
country-codes.IN=Indien
country-codes.ID=Indonesien
country-codes.IR=Iran
country-codes.IQ=Irak
country-codes.IE=Irland
country-codes.IL=Israel
country-codes.IT=Italien
country-codes.JM=Jamaica
country-codes.JP=Japan
country-codes.JO=Jordanien
country-codes.KZ=Kazakstan
country-codes.KE=Kenya
country-codes.KI=Kiribati
country-codes.KP=Korea North
country-codes.KR=Sydkorea
country-codes.KW=Kuwait
country-codes.KG=Kirgizistan
country-codes.LA=Laos
country-codes.LV=Lettland
country-codes.LB=Libanon
country-codes.LS=Lesotho
country-codes.LR=Liberia
country-codes.LY=Libyen
country-codes.LI=Liechtenstein
country-codes.LT=Litauen
country-codes.LU=Luxemburg
country-codes.MO=Macao
country-codes.MK=Makedonien
country-codes.MG=Madagaskar
country-codes.MW=Malawi
country-codes.MY=Malaysia
country-codes.MV=Maldiverna
country-codes.ML=Mali
country-codes.MT=Malta
country-codes.MH=Marshallöarna
country-codes.MQ=Martinique
country-codes.MR=Mauretanien
country-codes.YT=Mayotte
country-codes.MX=Mexico
country-codes.FM=Mikronesien
country-codes.MD=Moldavien
country-codes.MC=Monaco
country-codes.MN=Mongoliet
country-codes.MS=Montserrat
country-codes.MA=Marocko
country-codes.MZ=Moçambique
country-codes.MM=Myanmar
country-codes.NA=Namibia
country-codes.NR=Nauru
country-codes.NP=Nepal
country-codes.NL=Nederländerna
country-codes.NC=Nya Kaledonien
country-codes.NZ=Nya Zeeland
country-codes.NI=Nicaragua
country-codes.NE=Niger
country-codes.NG=Nigeria
country-codes.NU=Niue
country-codes.NF=Norfolköarna
country-codes.MP=Norra marianerna
country-codes.NO=Norge
country-codes.OM=Oman
country-codes.PW=Palau
country-codes.PA=Panama
country-codes.PG=Papua Nya Guinea
country-codes.PY=Paraguay
country-codes.PE=Peru
country-codes.PH=Filippinerna
country-codes.PL=Polen
country-codes.PT=Portugal
country-codes.PR=Puerto Rico
country-codes.QA=Qatar
country-codes.RE=Återförening
country-codes.RO=Rumänien
country-codes.RU=Ryssland
country-codes.RW=Rwanda
country-codes.SM=San Marino
country-codes.ST=Sao Tome &amp; Principe
country-codes.SA=Saudiarabien
country-codes.SN=Senegal
country-codes.CS=Serbien
country-codes.SC=Seychellerna
country-codes.SL=Sierra Leone
country-codes.SG=Singapore
country-codes.SK=Slovakien
country-codes.SI=Slovenien
country-codes.SB=Salomonöarna
country-codes.SO=Somalia
country-codes.ZA=Sydafrika
country-codes.ES=Spanien
country-codes.LK=Sri Lanka
country-codes.SH=St Helena
country-codes.KN=St. Kitts
country-codes.LC=Sankta Lucia
country-codes.SD=Sudan
country-codes.SR=Surinam
country-codes.SZ=Swaziland
country-codes.SE=Sverige
country-codes.CH=Schweiz
country-codes.SY=Syrien
country-codes.TW=Taiwan
country-codes.TJ=Tadzjikistan
country-codes.TH=Thailand
country-codes.TG=Togo
country-codes.TO=Tonga
country-codes.TT=Trinidad &amp; Tobago
country-codes.TN=Tunisien
country-codes.TR=Kalkon
country-codes.TM=Turkmenistan
country-codes.TC=Turkar &amp; Caicosöarna
country-codes.TV=Tuvalu
country-codes.UG=Uganda
country-codes.GB=Storbritannien
country-codes.UA=Ukraina
country-codes.AE=Förenade arabemiraten
country-codes.UY=Uruguay
country-codes.US=USA
country-codes.UZ=Uzbekistan
country-codes.VU=Vanuatu
country-codes.VA=Vatikanstaten
country-codes.VE=Venezuela
country-codes.VN=Vietnam
country-codes.VG=Jungfruöarna - Brittiska
country-codes.VI=Jungfruöarna - USA
country-codes.WF=Wallis &amp; Futuna
country-codes.YE=Jemen
country-codes.ZM=Zambia
country-codes.ZW=Zimbabwe
