#
# Copyright (C) 2016 Curity AB. All rights reserved.
#
# The contents of this file are the property of Curity AB.
# You may not copy or use this file, in either source code
# or executable form, except in compliance with terms
# set by Curity AB.
#
# For further information, please contact Curity AB.
#

register.meta.title=Registrera mobilnummer
register.page.title=Registrera mobilnummer
register.view.phone=Ange ditt mobilnummer
register.view.verify=Skicka verifikationskod
register.view.update-phonenumber=Uppdatera ditt telefonnummer
register.view.change-phonenumber=Ändra ditt telefonnummer
register.view.description=Uppdatera ditt telefonnmmer för att kunna använda det i inloggninsmetoder som använder sms.
register.view.placeholder=Telefonnummer
register.view.restart=Starta om
register.wait.view.authenticate=Klicka på länken som skickats till:
register.wait.view.restart=Börja om

register.error.validation.invalid.phonenumber=Telefonnumret är ogiltigt
register.error.validation.phonenumber.required=Du måste ange ett telefonnumer
register.error.validation.number-already-registered=Telefonnummer är redan registrerad
register.error.too-many-attempts=För många försök att registrera ett nytt telefonnummer. Försök igen om en stund.
register.error.restart=Något gick fel. Starta om
register.error.user.mismatch=Kontouppdatering misslyckades

register.view.country-code.label=Landskod
