#
# Copyright (C) 2016 Curity AB. All rights reserved.
#
# The contents of this file are the property of Curity AB.
# You may not copy or use this file, in either source code
# or executable form, except in compliance with terms
# set by Curity AB.
#
# For further information, please contact Curity AB.
#

register.meta.title=Register phone number
register.page.title=Register phone number
register.view.phone=Enter your phone number
register.view.verify=Send verification code
register.view.update-phonenumber=Update your phone number
register.view.change-phonenumber=Change phone number
register.view.description=Update your phone number to be able to use it to authenticate with sms methods.
register.view.placeholder=Phone Number
register.view.restart=Restart
register.wait.view.authenticate=Please authenticate using the SMS sent to:
register.wait.view.restart=Start over

register.error.validation.invalid.phonenumber=The phone number you entered is invalid
register.error.validation.phonenumber.required=You have to enter a phone number
register.error.validation.number-already-registered=The phone number you provided is already registered
register.error.too-many-attempts=Too many attempts to register a new phone number. Try again later.
register.error.restart=Something went wrong. Restart the process
register.error.user.mismatch=Account update failed

register.view.country-code.label=Country Code
