#
# Copyright (C) 2026 Curity AB. All rights reserved.
#
# The contents of this file are the property of Curity AB.
# You may not copy or use this file, in either source code
# or executable form, except in compliance with terms
# set by Curity AB.
#
# For further information, please contact Curity AB.
#

country-codes.DZ=Algeria
country-codes.AD=Andorra
country-codes.AO=Angola
country-codes.AI=Anguilla
country-codes.AG=Antigua &amp; Barbuda
country-codes.AR=Argentina
country-codes.AM=Armenia
country-codes.AW=Aruba
country-codes.AU=Australia
country-codes.AT=Austria
country-codes.AZ=Azerbaijan
country-codes.BS=Bahamas
country-codes.BH=Bahrain
country-codes.BD=Bangladesh
country-codes.BB=Barbados
country-codes.BY=Belarus
country-codes.BE=Belgium
country-codes.BZ=Belize
country-codes.BJ=Benin
country-codes.BM=Bermuda
country-codes.BT=Bhutan
country-codes.BO=Bolivia
country-codes.BA=Bosnia Herzegovina
country-codes.BW=Botswana
country-codes.BR=Brazil
country-codes.BN=Brunei
country-codes.BG=Bulgaria
country-codes.BF=Burkina Faso
country-codes.BI=Burundi
country-codes.KH=Cambodia
country-codes.CM=Cameroon
country-codes.CA=Canada
country-codes.CV=Cape Verde Islands
country-codes.KY=Cayman Islands
country-codes.CF=Central African Republic
country-codes.CL=Chile
country-codes.CN=China
country-codes.CO=Colombia
country-codes.KM=Comoros
country-codes.CG=Congo
country-codes.CK=Cook Islands
country-codes.CR=Costa Rica
country-codes.HR=Croatia
country-codes.CU=Cuba
country-codes.CY=Cyprus
country-codes.CZ=Czech Republic
country-codes.DK=Denmark
country-codes.DJ=Djibouti
country-codes.DM=Dominica
country-codes.DO=Dominican Republic
country-codes.EC=Ecuador
country-codes.EG=Egypt
country-codes.SV=El Salvador
country-codes.GQ=Equatorial Guinea
country-codes.ER=Eritrea
country-codes.EE=Estonia
country-codes.ET=Ethiopia
country-codes.FK=Falkland Islands
country-codes.FO=Faroe Islands
country-codes.FJ=Fiji
country-codes.FI=Finland
country-codes.FR=France
country-codes.GF=French Guiana
country-codes.PF=French Polynesia
country-codes.GA=Gabon
country-codes.GM=Gambia
country-codes.GE=Georgia
country-codes.DE=Germany
country-codes.GH=Ghana
country-codes.GI=Gibraltar
country-codes.GR=Greece
country-codes.GL=Greenland
country-codes.GD=Grenada
country-codes.GP=Guadeloupe
country-codes.GU=Guam
country-codes.GT=Guatemala
country-codes.GN=Guinea
country-codes.GW=Guinea - Bissau
country-codes.GY=Guyana
country-codes.HT=Haiti
country-codes.HN=Honduras
country-codes.HK=Hong Kong
country-codes.HU=Hungary
country-codes.IS=Iceland
country-codes.IN=India
country-codes.ID=Indonesia
country-codes.IR=Iran
country-codes.IQ=Iraq
country-codes.IE=Ireland
country-codes.IL=Israel
country-codes.IT=Italy
country-codes.JM=Jamaica
country-codes.JP=Japan
country-codes.JO=Jordan
country-codes.KZ=Kazakhstan
country-codes.KE=Kenya
country-codes.KI=Kiribati
country-codes.KP=Korea North
country-codes.KR=Korea South
country-codes.KW=Kuwait
country-codes.KG=Kyrgyzstan
country-codes.LA=Laos
country-codes.LV=Latvia
country-codes.LB=Lebanon
country-codes.LS=Lesotho
country-codes.LR=Liberia
country-codes.LY=Libya
country-codes.LI=Liechtenstein
country-codes.LT=Lithuania
country-codes.LU=Luxembourg
country-codes.MO=Macao
country-codes.MK=Macedonia
country-codes.MG=Madagascar
country-codes.MW=Malawi
country-codes.MY=Malaysia
country-codes.MV=Maldives
country-codes.ML=Mali
country-codes.MT=Malta
country-codes.MH=Marshall Islands
country-codes.MQ=Martinique
country-codes.MR=Mauritania
country-codes.YT=Mayotte
country-codes.MX=Mexico
country-codes.FM=Micronesia
country-codes.MD=Moldova
country-codes.MC=Monaco
country-codes.MN=Mongolia
country-codes.MS=Montserrat
country-codes.MA=Morocco
country-codes.MZ=Mozambique
country-codes.MM=Myanmar
country-codes.NA=Namibia
country-codes.NR=Nauru
country-codes.NP=Nepal
country-codes.NL=Netherlands
country-codes.NC=New Caledonia
country-codes.NZ=New Zealand
country-codes.NI=Nicaragua
country-codes.NE=Niger
country-codes.NG=Nigeria
country-codes.NU=Niue
country-codes.NF=Norfolk Islands
country-codes.MP=Northern Marianas
country-codes.NO=Norway
country-codes.OM=Oman
country-codes.PW=Palau
country-codes.PA=Panama
country-codes.PG=Papua New Guinea
country-codes.PY=Paraguay
country-codes.PE=Peru
country-codes.PH=Philippines
country-codes.PL=Poland
country-codes.PT=Portugal
country-codes.PR=Puerto Rico
country-codes.QA=Qatar
country-codes.RE=Reunion
country-codes.RO=Romania
country-codes.RU=Russia
country-codes.RW=Rwanda
country-codes.SM=San Marino
country-codes.ST=Sao Tome &amp; Principe
country-codes.SA=Saudi Arabia
country-codes.SN=Senegal
country-codes.CS=Serbia
country-codes.SC=Seychelles
country-codes.SL=Sierra Leone
country-codes.SG=Singapore
country-codes.SK=Slovak Republic
country-codes.SI=Slovenia
country-codes.SB=Solomon Islands
country-codes.SO=Somalia
country-codes.ZA=South Africa
country-codes.ES=Spain
country-codes.LK=Sri Lanka
country-codes.SH=St. Helena
country-codes.KN=St. Kitts
country-codes.LC=St. Lucia
country-codes.SD=Sudan
country-codes.SR=Suriname
country-codes.SZ=Swaziland
country-codes.SE=Sweden
country-codes.CH=Switzerland
country-codes.SY=Syria
country-codes.TW=Taiwan
country-codes.TJ=Tajikstan
country-codes.TH=Thailand
country-codes.TG=Togo
country-codes.TO=Tonga
country-codes.TT=Trinidad &amp; Tobago
country-codes.TN=Tunisia
country-codes.TR=Turkey
country-codes.TM=Turkmenistan
country-codes.TC=Turks &amp; Caicos Islands
country-codes.TV=Tuvalu
country-codes.UG=Uganda
country-codes.GB=UK
country-codes.UA=Ukraine
country-codes.AE=United Arab Emirates
country-codes.UY=Uruguay
country-codes.US=USA
country-codes.UZ=Uzbekistan
country-codes.VU=Vanuatu
country-codes.VA=Vatican City
country-codes.VE=Venezuela
country-codes.VN=Vietnam
country-codes.VG=Virgin Islands - British
country-codes.VI=Virgin Islands - US
country-codes.WF=Wallis &amp; Futuna
country-codes.YE=Yemen
country-codes.ZM=Zambia
country-codes.ZW=Zimbabwe
