#
# Copyright (C) 2022 Curity AB. All rights reserved.
#
# The contents of this file are the property of Curity AB.
# You may not copy or use this file, in either source code
# or executable form, except in compliance with terms
# set by Curity AB.
#
# For further information, please contact Curity AB.
#

register.meta.title=Número de telefone do registro
register.page.title=Número de telefone do registro
register.view.phone=Digite seu número de telefone
register.view.verify=Enviar código de verificação
register.view.update-phonenumber=Atualize seu número de telefone
register.view.change-phonenumber=Mudar o número de telefone
register.view.description=Atualize seu número de telefone para poder utilizá-lo para autenticar com os métodos sms.
register.view.placeholder=Número de telefone
register.view.restart=Reiniciar
register.wait.view.authenticate=Autentique usando o SMS enviado para
register.wait.view.restart=Começar de novo
register.error.validation.invalid.phonenumber=O número de telefone que você inseriu é inválido
register.error.validation.phonenumber.required=Você tem que digitar um número de telefone
register.error.validation.number-already-registered=O número de telefone que você forneceu já está registrado
register.error.too-many-attempts=Muitas tentativas de registrar um novo número de telefone. Tente novamente mais tarde.
register.error.restart=Algo deu errado. Reiniciar o processo
register.error.user.mismatch=A atualização da conta falhou
register.view.country-code.label=Código do País
